name: generate-site
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
        with:
          token: ${{ secrets.PAT }}
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python build.py
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: identify
        run: |
          git config --global user.name 'Extremq'
          git config --global user.email 'extremq@users.noreply.github.com'
      - name: commit changed files
        run: git commit -m "[actions skip] Auto update views."
      - name: push changes
        run: git push